### ISSUE TITLE
Document the public API

### ISSUE THREAD

**Issue by KacperKluka** [nomtek/mistralai_client_dart#10]
We need to document the public-facing API of our SDK in order to make it more user-friendly and usable.

At the time of writing this issue, this means that we need to document the methods in the `mistralai_client_dart_base.dart` file. We can use the [official JS client API](https://github.com/mistralai/client-js) as a reference.

**Comment by gawi151** [comment]
Waiting for https://github.com/nomtek/mistralai_client_dart/pull/18 to be merged.
