### ISSUE TITLE
Automate the package release

### ISSUE THREAD

**Issue by KacperKluka** [nomtek/mistralai_client_dart#21]
We want to automate releases of our package to pub.dev and make sure that anyone can make a new release.

We should create a new workflow for Github Actions that would check and build the project and publish it to the pub.dev.

You may check https://dart.dev/tools/pub/automated-publishing for more info.

**Comment by gawi151** [comment]
~~We should also include FlutterFlow version automation.~~

No longer valid as we don't want to support FlutterFlow in the long run.
