### ISSUE TITLE
Add information about running code generation and the approach towards generated files

### ISSUE THREAD

**Issue by KacperKluka** [nomtek/mistralai_client_dart#58]
**Is your feature request related to a problem? Please describe.**
While working on the repository I wasn't sure how to run code generation and whether to commit/format the generated code.

**Describe the solution you'd like**
I think we should add some info about how to generate code and what to do with it afterwards to the `CONTRIBUTING.md` file.

**Describe alternatives you've considered**
N/A

**Comment by gawi151** [comment]
Agree totally. Could you @KacperKluka propose a change in a PR?

At the moment we commit generated code to the repo. So it's responsibility of the one that implements features/changes to generate files with `build_runner`. 

If you think we should do it differently then let's discuss ;)
